### PR TITLE
#164 updated glam & bevy_ecs types to match their `serde` implementation

### PR DESCRIPTION
**Pull request by bennoinbeta**

### CODE REVIEW

**Comment by bennoinbeta** [comment]
Would it be possible to generate like:
```
export type Vec2 = [number, number]
```
instead of
```
export type Vec2 = number[]
```

`number[]` is good enough but like `[number, number]` would be even more typesafe :)

**Comment by oscartbeaumont** [comment]
You could try `(i32, i32)` or `[i32; 2]`?

**Comment by bennoinbeta** [comment]
> You could try `(i32, i32)` or `[i32; 2]`?
> 
> If it's not clear with Serde transparent the first one will be `struct Demo((i32, i32));` not `struct Demo(i32, i32)`.

Ok `(f32, f32)` seems to work:
```rust
#[derive(Type)]
#[specta(remote = glam::Vec2, crate = crate, export = true)]
#[allow(dead_code)]
struct Vec2((f32, f32));
```
Result:
```ts
export type Vec2 = [number, number]
```

---

With `[f32; 2]` (as its rn implemented) it results in `number[]` though.
```rust
#[derive(Type)]
#[specta(remote = glam::Vec2, crate = crate, export = true)]
#[allow(dead_code)]
struct Vec2([f32; 2]);
```

Result:
```ts
export type Vec2 = number[]
```

---

so I'll change that quickly into a tuple  :)

**Comment by oscartbeaumont** [comment]
As of https://github.com/oscartbeaumont/specta/commit/7039fba7972935b3a64325250a3f46370ca034fa we now support `[T; N]` as a fixed size Typescript tuple.

**Comment by oscartbeaumont** [comment]
Thanks heaps for the PR!

**Pull request merged**
