### PR TITLE
`specta-impls` crate

### PR DESCRIPTION
**Pull request by oscartbeaumont**
This code is cursed but I think it's the way.

I want Specta v2 to be able to develop an ecosystem.

That means independent crates implementing `specta::Type` instead of it being on `specta` to do it for them. 

If `specta` maintains the impls for downstream crates if any of the downstream crates have a major version bump specta either has to also do a major release or introduce a new feature Eg. `tauri`, `tauri2`, etc.

Specta doing a major release is not a viable option because *every* downstream crate that has provided a Specta implementation will also need to be upgraded. Hence downstream maintainers don't wanna take on crates that are gonna commonly have major version bumps. This whole thing is also bad for everyone using the libraries because if the versions mismatch between different libraries your using you are just outta luck.

By introducing a `specta-impls` crate, and some cursed code to avoid the orphan rule we can allow `specta-impls` to do major releases without breaking 

This allows me to decouple major versions of the Specta features for other crates from the Specta core traits.

### CODE REVIEW

**Comment by oscartbeaumont** [comment]
Should also add a `specta_core` crate for the traits cause they hopefully won't change *every* once I am happy with them. Mostly just gonna refine the `generics` bit.

**Comment by appinteractive** [comment]
any update on that one?

**Comment by oscartbeaumont** [comment]
Not at the moment. None of this should matter much to an end-user of Specta though.

For now, you can use the features on the Specta crate itself or if you own a downstream crate implement `Type` within it.

**Comment by oscartbeaumont** [comment]
I'm closing this as I am very certain it's not the correct way to achieve the objective.

Due to how Cargo's semver works we can make downstream crates depend on `2.0.0-rc.x` and they will automatically "upgrade" to `2.x.x` as they are a semver match. This means as long as we implement the trait using the macro the only things that can't change are:
 - `specta::Type` export
 - Any `#[specta(...)]` attribute being used.

We are using this method with `tauri` right now but I will follow up with the rest of the implementation before we launch Specta v2 as stable.

**Pull request closed without merging**
